# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 321b1349b1145c341e0fc6dfa8cb09a4b20aade87ec21040957306feec2c9b8d852ea7cfae9ed64f9a31e723ccff014ac0e33eac9e62add31697dd9d2198945c

test:
  secret_key_base: b3b9a9d185abb55037587b64645110734f126a09a4edd3fd46788fc7683fa9f316fdbf5f40579c2d4538a586a7cbc40ca92ca5898e7f464f235e3db90e93f4fa

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
